apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-{{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version }}
  labels:
{{- include "mychart.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        type: webapp
    spec:
      containers:
        - name: mywebapp
          {{- with .Values.webapp }}
          image: nginx:{{ .imageTag }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      type: webapp