apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-ro
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    path: /
    server: fs-04df12f08b1b61f65.efs.us-east-1.amazonaws.com
  persistentVolumeReclaimPolicy: Retain