apiVersion: v1
kind: Pod
metadata:
  name: webapp-database
  labels:
    app: mysql
spec:
  containers:
    - image: mysql
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: test

---

apiVersion: v1
kind: Service
metadata:
  name: mysv-database
spec:
  ports:
    - port: 8081
      targetPort: 3306
  selector:
    type: database