apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    type: webapp
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        type: webapp
    spec:
      containers:
        - name: mywebapp
          image: nginx:latest #v1
  replicas: 0
  selector:
    matchLabels:
      type: webapp
