apiVersion: v1
kind: Pod
metadata:
  name: student-app
spec:
#  imagePullSecrets:
#    - name: dockerhubsecret
  containers:
    - name: student-app
      image: nginx
      ports:
        - containerPort: 80
      imagePullPolicy: Always

---

apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - name: app
      image: nginx
      ports:
        - containerPort: 80
      imagePullPolicy: Always
